name: build
on: [push, workflow_dispatch]
jobs:
  pre-publish-job:
    runs-on: ubuntu-latest
    steps:
      - name: branch checkout
        uses: actions/checkout@v4
      - name: node install
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: package install
        run: npm ci
      - name: lint fix
        run: |
          npm run lint
          echo "checking lint"
      - name: testing
        run: |
          npm run test
          echo "checking tests"
  build:
    runs-on: ubuntu-latest
    needs: pre-publish-job
    steps:
      - name: branch checkout
        uses: actions/checkout@v4
      - name: node install
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: package install
        run: npm ci
      - name: build package
        run: npm run build
      - name: uploading artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-file
          path: |
            dist
            package.json
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: get build
        uses: actions/download-artifact@v4
        with:
          name: dist-file
      - name: output files
        run: ls
          

