name: Pr
on: 
  pull_request:
    types:
      - opened
      - edited
      - reopened
    branches:
      - master
      - main
      - 'dev-*'
      - 'feat/**'
  workflow_dispatch:
  push:
    branches:
      - master
      - main
      - 'dev-*'
      - 'feat/**'
jobs:
  pr-handler:
    runs-on: ubuntu-latest
    steps:
      - name: PR or push event
        run: echo "${{toJSON(github.event)}}"