name: build
on: push
jobs:
  pre-publish-job:
    runs-on: ubuntu-latest
    steps:
      - name: branch checkout
        uses: actions/checkout@v4
      - name: node install
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: package install
        run: npm ci
      - name: lint fix
        run: |
          npm run lint
          echo "checking lint"
      - name: testing
        run: |
          npm run test
          echo "checking tests"
  build:
    runs-on: ubuntu-latest
    needs: pre-publish-job
    steps:
      - name: branch checkout
        uses: actions/checkout@v4
      - name: node install
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: package install
        run: npm ci
      - name: build
        run: |
          npm run build
          echo "building"
